production:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      enable_starttls_auto: true
      address: "smtp.gmail.com"
      port: 587
      domain: "example.com"
      authentication: :plain
      user_name: "testgabriel44@gmail.com"
      password: "Statistik1234"

  # E-Mail-Empfang Konfiguration
  mail_handler:
    enabled: true
    unknown_user: "create"  # Erstellt neue Benutzer wenn unbekannt
    no_permission_check: false  # Sicherheitscheck aktiviert
    no_account_notice: true  # Benachrichtigung bei neuem Account
    default_group: "users"  # Standardgruppe für neue Benutzer
    project_from_subaddress: true  # Projekt aus E-Mail-Adresse ermitteln
    issue_attributes:
      tracker: "Support"  # Standard-Tracker
      priority: "Normal"  # Standard-Priorität
      status: "New"      # Standard-Status