
production:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      enable_starttls_auto: true
      address: smtp.gmail.com
      port: 587
      domain: gmail.com
      authentication: :plain
      user_name: "yfwy ykxq bwcs dtlu"
      password: "hier_ihr_app_passwort_einfügen"  # Das 16-stellige App-Passwort von Google

default:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      enable_starttls_auto: true
      address: smtp.gmail.com
      port: 587
      domain: gmail.com
      authentication: :plain
      user_name: "yfwy ykxq bwcs dtlu"
      password: "hier_ihr_app_passwort_einfügen"  # Das 16-stellige App-Passwort von Google